// =================================================================================================
// ⚠️ This file is automatically generated by the deployment script. Any manual changes will be lost.
// =================================================================================================
import { Address } from "viem";

// The chain ID of the network where the contracts are deployed
export const CHAIN_ID = 13390 as const;

// The address of the MeeChainToken (MCT) contract
export const MCT_TOKEN_ADDRESS: Address = "0x5FbDB2315678afecb367f032d93F642f64180aa3";

// The address of the MeeBotNFT contract
export const MEEBOT_NFT_ADDRESS: Address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512";

// The address of the NeonovaPortal contract
export const PORTAL_ADDRESS: Address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0";

// A collection of all contract addresses
export const CONTRACT_ADDRESSES = {
  mct: MCT_TOKEN_ADDRESS,
  nft: MEEBOT_NFT_ADDRESS,
  portal: PORTAL_ADDRESS,
} as const;
